### ISSUE TITLE
Export the repository url from the module

### ISSUE THREAD

**Issue by yeger00** [TechToSpeech/terraform-aws-ecr-mirror#4]
Hi,
Thanks you for writing this module. We had the exact same problem as you mentioned in the README and it solves it well.
A nice addition to the module can be exporting the repository URL (like `$3.dkr.ecr.$2.amazonaws.com/$4:$5` in the [docker_pullpush.sh](https://github.com/TechToSpeech/terraform-aws-ecr-mirror/blob/f67d2cf/docker_pullpush.sh#L10) file).
It will be easier to use it in other modules.

Let me know what you think.
Thanks,
Avi

**Comment by petewilcock** [comment]
Heya, so the module relies on the fact that the ECR repository already exists - it doesn't create it for you. So with that said, the repository is probably being created from another resource in terraform (outside of this module) and the export for the repo name would come from there?

**Comment by yeger00** [comment]
I want to have "one source of truth" regarding the creation of the repository URL. For example, the ECR repository doesn't provide the URL with the tag, because it doesn't exist yet (the string concatenation in your script).

**Comment by petewilcock** [comment]
It's quite easy to compute, but it's also no problem to add it to the module as an explicit output so I'll include that in the next update.

**Comment by yeger00** [comment]
Coo, thanks!

**Comment by petewilcock** [comment]
Now added @yeger00 - took a while 😅
