### ISSUE TITLE
Allow specifying one (or multiple) platform targets

### ISSUE THREAD

**Issue by blimmer** [TechToSpeech/terraform-aws-ecr-mirror#5]
Currently, if I run this from my M1 MacBook Pro, if the mirrored image has an `arm64` platform option, that's what gets mirrored to ECR. In many cases, I want to push the `amd64` architecture version instead, because that's what I'm using in ECS Fargate.

You can specify an architecture like this:

```
docker pull --platform linux/amd64 wordpress:php7.4-apache
```

So it'd be nice to be able to specify your target architecture(s).

**Comment by petewilcock** [comment]
Funny you mention this, I had the changes prepped locally for my testing for Graviton on serverless static wordpress. You reminded me to push it and it's now released in `0.0.8`.

**Comment by blimmer** [comment]
Amazing, thank you!
